version: "3.3"
services:

 facteuren:
  build: .
  networks:
   - isolated_nw2
  restart: on-failure
  volumes:
   - /tmp
  container_name: facteuren
  depends_on:
   - pgdben
 pgdben:
  image: postgres:15.0
  ports:
   - 5433:5432
  networks:
   - isolated_nw2
  volumes:
   - db-data:/var/lib/postgresql/data
  environment:
   POSTGRES_DB: bouteille
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: superFacteurBouteille2052
  container_name: postgresen

networks:
 isolated_nw2:
  driver: bridge

volumes:
 db-data:
  driver: local